import crypto from "crypto";
const SUPABASE_URL=process.env.SUPABASE_URL;const SERVICE_ROLE_KEY=process.env.SUPABASE_SERVICE_ROLE_KEY;const RESEND_API_KEY=process.env.isdo_registration_RESEND_API_KEY||process.env.RESEND_API_KEY;const RESEND_FROM_EMAIL=process.env.RESEND_FROM_EMAIL||"ISDO'27 <onboarding@resend.dev>";const RESEND_REPLY_TO=process.env.RESEND_REPLY_TO||"";
export default async function handler(req,res){if(req.method!=="POST")return res.status(405).json({error:"Method not allowed"});if(!SUPABASE_URL||!SERVICE_ROLE_KEY)return res.status(500).json({error:"Server configuration is incomplete."});const p=req.body||{},player=p.player||{},memberships=Array.isArray(p.memberships)?p.memberships:[],meals=Array.isArray(p.meals)?p.meals:[],legal=Array.isArray(p.legal_acceptances)?p.legal_acceptances:[];try{for(const f of["first_name","last_name","birth_date","nationality","email","origin_club_id"])if(!player[f])throw bad("Missing field: "+f);const participantType=["player","coach","other"].includes(player.participant_type)?player.participant_type:"player";if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(player.email))throw bad("Invalid email address.");if(participantType==="player"){if(memberships.length<1||memberships.length>2)throw bad("One or two team memberships are required for players.");await validateMemberships(memberships,player.origin_club_id)}else if(memberships.length){throw bad("Team memberships are only available for players.");}const docs=await select("legal_documents","select=id&active=eq.true");if(!docs.length)throw bad("Legal documents are not configured.");const accepted=new Set(legal.filter(x=>x.accepted).map(x=>x.legal_document_id));if(docs.some(d=>!accepted.has(d.id)))throw bad("All legal documents must be accepted.");const created=await insert("players",{...player,participant_type:participantType,jersey_number:participantType==="player"?(player.jersey_number||null):null,registration_status:"complete",updated_at:new Date().toISOString()},true);const playerId=created.id;try{if(memberships.length)await insert("player_team_memberships",memberships.map(m=>({player_id:playerId,team_id:m.team_id,membership_order:m.membership_order,captain:false,vice_captain:false})));if(meals.length)await insert("player_meals",meals.map(x=>({player_id:playerId,meal_day_id:x.meal_day_id,sandwich_option_id:x.ordered?x.sandwich_option_id:null,ordered:!!x.ordered})));await insert("player_legal_acceptances",legal.map(x=>({player_id:playerId,legal_document_id:x.legal_document_id,accepted:true,accepted_at:new Date().toISOString()})));const editToken=crypto.randomBytes(32).toString("base64url"),tokenHash=hashToken(editToken);await insert("player_edit_tokens",{player_id:playerId,token_hash:tokenHash});const editUrl=`${siteOrigin(req)}/edit.html?token=${encodeURIComponent(editToken)}`;let emailSent=false;try{emailSent=await sendConfirmationEmail({to:player.email,firstName:player.first_name,editUrl,participantType})}catch(emailError){console.error("ISDO confirmation email failed:",emailError)}return res.status(200).json({ok:true,player_id:playerId,edit_url:editUrl,email_sent:emailSent})}catch(err){await del("players",`id=eq.${encodeURIComponent(playerId)}`);throw err}}catch(err){return res.status(err.statusCode||400).json({error:err.message||"Registration could not be saved."})}}
async function validateMemberships(memberships,originClubId){const teams=await select("teams",`select=id,category_id,active&id=in.(${memberships.map(x=>encodeURIComponent(x.team_id)).join(",")})`);if(teams.length!==memberships.length)throw bad("Invalid team selection.");if(new Set(teams.map(t=>t.category_id)).size!==teams.length)throw bad("The two categories must be different.");for(const m of memberships){const a=await select("team_origin_club_access",`select=id&team_id=eq.${encodeURIComponent(m.team_id)}&origin_club_id=eq.${encodeURIComponent(originClubId)}`);if(!a.length)throw bad("A selected team is not available for this club of origin.")}}
function siteOrigin(req){const proto=(req.headers["x-forwarded-proto"]||"https").split(",")[0].trim(),host=(req.headers["x-forwarded-host"]||req.headers.host||"registration-isdo.vercel.app").split(",")[0].trim();return `${proto}://${host}`}
function hashToken(token){return crypto.createHash("sha256").update(token).digest("hex")}
async function sendConfirmationEmail({to,firstName,editUrl,participantType}){if(!RESEND_API_KEY){console.warn("RESEND API key is missing. Registration saved without email.");return false}const label=participantType==="player"?"player":participantType==="coach"?"coach":"participant";const body={from:RESEND_FROM_EMAIL,to:[to],subject:"ISDO'27 – Registration confirmed",html:`<!doctype html><html><body style="margin:0;padding:28px;background:#f4f5f7;font-family:Arial,Helvetica,sans-serif;color:#171923"><div style="max-width:620px;margin:auto;background:#fff;border:1px solid #e5e7eb;border-radius:16px;padding:30px"><div style="font-size:12px;letter-spacing:1.2px;text-transform:uppercase;font-weight:700;color:#e52d4d">International Sharks Dodgeball Open</div><h1>Registration confirmed ✓</h1><p>Hi ${htmlEscape(firstName)},</p><p>Your ${label} registration for <strong>ISDO'27</strong> has been saved successfully.</p><p>Keep the private link below. You can use it later to update your registration or lunch choices without creating an account.</p><p style="text-align:center"><a href="${htmlEscape(editUrl)}" style="display:inline-block;background:#e52d4d;color:#fff;text-decoration:none;font-weight:700;padding:13px 22px;border-radius:10px">Edit my registration</a></p><p style="font-size:13px;word-break:break-all"><a href="${htmlEscape(editUrl)}">${htmlEscape(editUrl)}</a></p><p style="font-size:13px;color:#6b7280">Keep this link private. Anyone who has it can modify your registration.</p></div></body></html>`};if(RESEND_REPLY_TO)body.reply_to=RESEND_REPLY_TO;const response=await fetch("https://api.resend.com/emails",{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${RESEND_API_KEY}`},body:JSON.stringify(body)});if(!response.ok){let details="";try{details=JSON.stringify(await response.json())}catch{details=await response.text()}throw new Error(`Resend returned ${response.status}: ${details}`)}return true}
function htmlEscape(v){return String(v??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;")}
function headers(){return{apikey:SERVICE_ROLE_KEY,Authorization:`Bearer ${SERVICE_ROLE_KEY}`}}
async function select(table,q){const r=await fetch(`${SUPABASE_URL}/rest/v1/${table}?${q}`,{headers:headers()});if(!r.ok)throw await er(r);return r.json()}
async function insert(table,body,single=false){const r=await fetch(`${SUPABASE_URL}/rest/v1/${table}`,{method:"POST",headers:{...headers(),"Content-Type":"application/json",Prefer:single?"return=representation":"return=minimal"},body:JSON.stringify(body)});if(!r.ok)throw await er(r);if(single)return (await r.json())[0]}
async function del(table,q){await fetch(`${SUPABASE_URL}/rest/v1/${table}?${q}`,{method:"DELETE",headers:headers()})}
async function er(r){let d={};try{d=await r.json()}catch{}const x=new Error(d.message||d.error||"Database request failed.");x.statusCode=r.status>=500?500:400;return x}
function bad(m){const e=new Error(m);e.statusCode=400;return e}
