const db=window.isdoSupabase,$=id=>document.getElementById(id);let session=null,selected=null;
document.addEventListener("DOMContentLoaded",async()=>{bind();const r=await db.auth.getSession();session=r.data.session;if(session)load();});
function bind(){ $("loginForm").onsubmit=login;$("logout").onclick=()=>db.auth.signOut();$("closeDialog").onclick=()=>$("dialog").close();$("captainBtn").onclick=()=>role("captain");$("viceBtn").onclick=()=>role("vice_captain");$("removeBtn").onclick=remove;db.auth.onAuthStateChange((_e,s)=>{session=s;s?load():showLogin()});}
async function login(ev){ev.preventDefault();const {error}=await db.auth.signInWithPassword({email:$("email").value.trim().toLowerCase(),password:$("password").value});if(error){$("loginMsg").textContent=error.message;$("loginMsg").classList.remove("hidden")}}
function showLogin(){$("dashboard").classList.add("hidden");$("login").classList.remove("hidden")}
async function api(url,opt={}){const r=await fetch(url,{...opt,headers:{...(opt.headers||{}),"Content-Type":"application/json",Authorization:`Bearer ${session.access_token}`}});const d=await r.json();if(!r.ok)throw new Error(d.error||"Request failed");return d}
async function load(){ $("login").classList.add("hidden");$("dashboard").classList.remove("hidden");try{const d=await api("/api/manager-roster");render(d)}catch(e){alert(e.message)}}
function render(d){$("clubName").textContent=d.clubs.length===1?d.clubs[0].name:"My Clubs";$("managerEmail").textContent=d.manager_email;const all=d.teams.flatMap(t=>t.players);$("teamCount").textContent=d.teams.length;$("rosterCount").textContent=all.length;$("completeCount").textContent=all.filter(x=>x.registration_complete).length;$("missingMealsCount").textContent=all.filter(x=>!x.meals_complete).length;const box=$("teams");box.innerHTML="";d.teams.forEach(t=>{const a=document.createElement("article");a.className="team";a.innerHTML=`<div class="teamHead"><div><span class="badge role">${esc(t.category)}</span><h2>${esc(t.team_name)}</h2></div><b>${t.players.length} players</b></div>`;t.players.forEach(p=>{const r=document.createElement("div");r.className="player";r.innerHTML=`<div><b>${esc(p.first_name)} ${esc(p.last_name)}</b> ${p.captain?'<span class="badge role">Captain</span>':p.vice_captain?'<span class="badge role">Vice-captain</span>':''}</div><div>#${esc(p.jersey_number||"—")}</div><div class="mobileHide"><span class="badge ${p.registration_complete?'ok':'warn'}">${p.registration_complete?'Complete':'Incomplete'}</span></div><div class="mobileHide"><span class="badge ${p.meals_complete?'ok':'warn'}">${p.meals_complete?'Meals ✓':'Meals missing'}</span></div>`;r.onclick=()=>openPlayer(t,p);a.appendChild(r)});box.appendChild(a)})}
function openPlayer(t,p){selected={t,p};$("dCat").textContent=t.category;$("dName").textContent=`${p.first_name} ${p.last_name}`;$("dTeam").textContent=t.team_name;$("dJersey").textContent=p.jersey_number||"—";$("dReg").textContent=p.registration_complete?"Complete":"Incomplete";$("dMeals").textContent=p.meals_complete?"Completed":"Missing";$("captainBtn").textContent=p.captain?"Remove captain":"Set as captain";$("viceBtn").textContent=p.vice_captain?"Remove vice-captain":"Set as vice-captain";$("dialog").showModal()}
async function role(field){await api("/api/manager-membership",{method:"PATCH",body:JSON.stringify({membership_id:selected.p.membership_id,field,value:!selected.p[field]})});$("dialog").close();load()}
async function remove(){if(!confirm(`Remove ${selected.p.first_name} ${selected.p.last_name} from ${selected.t.team_name}?`))return;await api("/api/manager-membership",{method:"DELETE",body:JSON.stringify({membership_id:selected.p.membership_id})});$("dialog").close();load()}
function esc(v){return String(v??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;")}
