const SUPABASE_URL=process.env.SUPABASE_URL;const SECRET=process.env.SUPABASE_SERVICE_ROLE_KEY;
function H(){return{apikey:SECRET,Authorization:`Bearer ${SECRET}`}}
async function user(req){const t=(req.headers.authorization||"").replace("Bearer ","");if(!t)throw E(401,"Not signed in.");const r=await fetch(`${SUPABASE_URL}/auth/v1/user`,{headers:{apikey:SECRET,Authorization:`Bearer ${t}`}});if(!r.ok)throw E(401,"Session expired.");return r.json()}
async function q(table,query){const r=await fetch(`${SUPABASE_URL}/rest/v1/${table}?${query}`,{headers:H()});if(!r.ok)throw await RE(r);return r.json()}
async function patch(table,query,body){const r=await fetch(`${SUPABASE_URL}/rest/v1/${table}?${query}`,{method:"PATCH",headers:{...H(),"Content-Type":"application/json"},body:JSON.stringify(body)});if(!r.ok)throw await RE(r)}
async function del(table,query){const r=await fetch(`${SUPABASE_URL}/rest/v1/${table}?${query}`,{method:"DELETE",headers:H()});if(!r.ok)throw await RE(r)}
async function RE(r){let d={};try{d=await r.json()}catch{}return E(r.status,d.message||"Database error")}
function E(s,m){const e=new Error(m);e.statusCode=s;return e}

export default async function handler(req,res){if(req.method!=="GET")return res.status(405).json({error:"Method not allowed"});try{const u=await user(req),roles=await q("user_roles",`select=role&user_id=eq.${u.id}`),admin=roles.some(x=>x.role==="admin");let clubIds;if(admin){clubIds=(await q("clubs","select=id&active=eq.true")).map(x=>x.id)}else{clubIds=(await q("club_managers",`select=club_id&user_id=eq.${u.id}`)).map(x=>x.club_id)}if(!clubIds.length)throw E(403,"No club assigned.");const clubs=await q("clubs",`select=id,name&id=in.(${clubIds.join(",")})`),teams=await q("teams",`select=id,managing_club_id,category_id,display_name&active=eq.true&managing_club_id=in.(${clubIds.join(",")})`),cats=await q("categories","select=id,name"),cat=new Map(cats.map(x=>[x.id,x.name])),club=new Map(clubs.map(x=>[x.id,x.name]));if(!teams.length)return res.json({manager_email:u.email,clubs,teams:[]});const tids=teams.map(x=>x.id),m=await q("player_team_memberships",`select=id,player_id,team_id,captain,vice_captain&team_id=in.(${tids.join(",")})`),pids=[...new Set(m.map(x=>x.player_id))],players=pids.length?await q("players",`select=id,first_name,last_name,jersey_number,registration_status&id=in.(${pids.join(",")})`):[],days=await q("meal_days","select=id&active=eq.true"),meals=pids.length?await q("player_meals",`select=player_id,meal_day_id&player_id=in.(${pids.join(",")})`):[],pm=new Map(players.map(x=>[x.id,x])),mb=new Map();meals.forEach(x=>{if(!mb.has(x.player_id))mb.set(x.player_id,new Set());mb.get(x.player_id).add(x.meal_day_id)});const out=teams.map(t=>({id:t.id,category:cat.get(t.category_id),team_name:t.display_name||club.get(t.managing_club_id),players:m.filter(x=>x.team_id===t.id).map(x=>{const p=pm.get(x.player_id);return p&&{membership_id:x.id,first_name:p.first_name,last_name:p.last_name,jersey_number:p.jersey_number,registration_complete:p.registration_status==="complete",meals_complete:(mb.get(p.id)?.size||0)===days.length,captain:x.captain,vice_captain:x.vice_captain}}).filter(Boolean)}));res.json({manager_email:u.email,clubs,teams:out})}catch(e){res.status(e.statusCode||500).json({error:e.message})}}
